### PR TITLE
Install additional packages via pip

### PR DESCRIPTION
**Pull request by oxr463**
Bug: https://github.com/mhausenblas/mkdocs-deploy-gh-pages/issues/2

### CODE REVIEW

**Comment by mhausenblas** [comment]
Awesome, thanks a lot @oxr463! Can you sign off your PR pls so the DCO is sorted?

**Comment by oxr463** [comment]
@mhausenblas done.

**Comment by mhausenblas** [comment]
Tanks a lot @oxr463 ... now we have a little merge conflict. Mind fixing this?

**Comment by mhausenblas** [comment]
Super cool, thanks a million @oxr463!

**Pull request merged**
